#!/bin/bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

REPO="claudio3g/orchestra-ai"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# --- AI_BOOTSTRAP.md (self-sufficient: rules + inline file list) ---
{
  echo "# AI Bootstrap — Orchestra AI"
  echo ""
  echo "> **Ultimo aggiornamento:** $NOW"
  echo "> **Branch:** \`$BRANCH\`"
  echo "> **Repo:** $REPO"
  echo ""
  echo "---"
  echo ""
  echo "## ⚠️ REGOLE FONDAMENTALI (leggere prima di tutto)"
  echo ""
  echo "### Anti-hallucination policy"
  echo ""
  echo "1. **Non inventare MAI** contenuti di file, struttura di directory o nomi di file."
  echo "2. **La lista autorevole è nella sezione \"File tracciati\" qui sotto**. Nessun file esiste al di fuori di quella lista."
  echo "3. **Ogni affermazione sul contenuto del repository deve essere supportata da un fetch effettivo**."
  echo "4. **LLM NON sanno decodificare base64 in modo affidabile**. NON usare l'API GitHub che ritorna base64. Usa uno dei metodi plain-text della sezione successiva."
  echo "5. **Se non riesci a leggere un file, dì esplicitamente \"non ho potuto leggere X\"**. Mai inventare."
  echo ""
  echo "---"
  echo ""
  echo "## 1. Come accedere ai file (metodi plain-text)"
  echo ""
  echo "### Metodo 1 — jsDelivr CDN (consigliato, plain text)"
  echo ""
  echo "    https://cdn.jsdelivr.net/gh/$REPO@$BRANCH/<path>"
  echo ""
  echo "Esempio:"
  echo ""
  echo "    https://cdn.jsdelivr.net/gh/$REPO@$BRANCH/README.it.md"
  echo ""
  echo "### Metodo 2 — Jina Reader (plain text, converte qualsiasi URL)"
  echo ""
  echo "    https://r.jina.ai/https://raw.githubusercontent.com/$REPO/$BRANCH/<path>"
  echo ""
  echo "### Metodo 3 — GitHub API (RESTITUISCE BASE64, sconsigliato)"
  echo ""
  echo "    https://api.github.com/repos/$REPO/contents/<path>"
  echo ""
  echo "Il campo \`content\` è base64. Da usare solo se gli altri metodi falliscono e SOLO con decodifica programmatica (non manuale)."
  echo ""
  echo "---"
  echo ""
  echo "## 2. File tracciati (GROUND TRUTH)"
  echo ""
  echo "**Nessun file esiste al di fuori di questa lista. Se un file non è qui, NON ESISTE.**"
  echo ""
  echo "| Path | Byte |"
  echo "|------|------|"
  git ls-files | while IFS= read -r f; do
    [ -f "$f" ] || continue
    size=$(stat -c%s "$f" 2>/dev/null || echo "?")
    printf '| `%s` | %s |\n' "$f" "$size"
  done
  echo ""
  echo "**Totale: $(git ls-files | wc -l) file tracciati.**"
  echo ""
  echo "---"
  echo ""
  echo "## 3. Percorsi reali del progetto"
  echo ""
  echo "| Cosa | Percorso |"
  echo "|------|----------|"
  echo "| Repository locale | /home/claudio/ai-sessioni |"
  echo "| Remote Git | git@github.com:$REPO.git |"
  echo "| Branch principale | main |"
  echo "| Branch secondario | dual-gpu-step1 |"
  echo "| Workflow AI | .github/workflows/ai-commit.yml |"
  echo "| Script dispatch | ~/ai-dispatch.sh |"
  echo "| Token GitHub | ~/.orchestra_github_token |"
  echo "| RAG service | rag/rag_service.py (porta 6335) |"
  echo ""
  echo "---"
  echo ""
  echo "## 4. Workflow AI — commit automatico"
  echo ""
  echo "1. L'AI genera una patch in formato diff"
  echo "2. La patch viene inviata via \`curl\` a GitHub API"
  echo "3. Il workflow \`.github/workflows/ai-commit.yml\` si attiva:"
  echo "   - \`validate\`: verifica payload"
  echo "   - \`sandbox-test\`: applica la patch ed esegue 5 test"
  echo "   - \`commit-push\`: se i test passano, esegue questo script, committa, pusha"
  echo ""
  echo "Trigger manuale:"
  echo ""
  echo "    ~/ai-dispatch.sh <patch.diff> \"<messaggio>\" [branch]"
  echo ""
  echo "---"
  echo ""
  echo "## 5. Cose da NON fare"
  echo ""
  echo "- ❌ \`git reset --hard\` senza backup"
  echo "- ❌ \`git push --force\` (usare \`--force-with-lease\`)"
  echo "- ❌ committare: token, segreti, \`rag/.file_hash_cache.json\`"
  echo "- ❌ esporre i servizi pubblicamente"
  echo "- ❌ **usare l'API GitHub per leggere file** (base64 non decodificabile)"
  echo "- ❌ **inventare file non presenti nella sezione 2**"
  echo ""
  echo "---"
  echo ""
  echo "## 6. Contesto hardware"
  echo ""
  echo "- CPU: Intel i9 (nix-i9)"
  echo "- GPU: RTX 3090 (24 GB) + RTX 4060 Laptop (8 GB)"
  echo "- OS: Ubuntu 24.04"
  echo "- Runtime AI: Ollama + Open WebUI + Qdrant + RAG custom"
  echo "- Migrazione dual-GPU: in corso (branch \`dual-gpu-step1\`)"
  echo ""
} > AI_BOOTSTRAP.md

# --- AI_CONTEXT.md (bundle opzionale) ---
KEY_FILES=(
  "README.it.md"
  "AI_BOOTSTRAP.md"
  ".github/workflows/ai-commit.yml"
  ".gitignore"
  "start_ai_stack.sh"
)

{
  echo "# AI Context — Orchestra AI"
  echo ""
  echo "Bundle dei file chiave, concatenati per un singolo fetch (opzionale)."
  echo ""
  echo "> Generato: $NOW"
  echo "> Branch: \`$BRANCH\`"
  echo ""
  echo "---"
  echo ""
  for f in "${KEY_FILES[@]}"; do
    if [ -f "$f" ]; then
      echo "## File: \`$f\`"
      echo ""
      echo '```'
      head -c 50000 "$f"
      echo ""
      echo '```'
      echo ""
      echo "---"
      echo ""
    fi
  done
} > AI_CONTEXT.md

echo "OK: AI_BOOTSTRAP.md ($(wc -c < AI_BOOTSTRAP.md) byte)"
echo "OK: AI_CONTEXT.md ($(wc -c < AI_CONTEXT.md) byte)"
